"""add authentication fields to users

Revision ID: 5a3d726a2b89
Revises: 3d5af20c1a09
Create Date: 2026-06-18 13:18:45.718791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3d726a2b89'
down_revision: Union[str, Sequence[str], None] = '3d5af20c1a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'hashed_password',
            sa.String(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
